const fs=require('fs');const {JSDOM,VirtualConsole}=require('jsdom');
const file=process.argv[2]||'index.html';const html=fs.readFileSync(file,'utf8');const vc=new VirtualConsole();const errs=[];vc.on('jsdomError',e=>errs.push(String(e.message||e)));
const dom=new JSDOM(html,{runScripts:'dangerously',pretendToBeVisual:true,url:'https://x.vercel.app/',virtualConsole:vc,beforeParse(w){
 w.fetch=()=>Promise.resolve({ok:true,json:()=>Promise.resolve({}),text:()=>Promise.resolve('')});
 w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){},addListener(){},removeListener(){}});
 w.scrollTo=()=>{};w.print=()=>{};w.open=()=>({document:{write(){},close(){}},print(){},close(){}});
 w.navigator.serviceWorker={register:()=>Promise.resolve({addEventListener(){},update(){}}),addEventListener(){},controller:null,ready:Promise.resolve({})};
 w.indexedDB={open:()=>({addEventListener(){}})};
 w.AudioContext=function(){return{state:'running',resume(){},createOscillator:()=>({connect(){},start(){},stop(){},frequency:{},type:''}),createGain:()=>({connect(){},gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}}}),destination:{},currentTime:0};};
 w.supabase={createClient:()=>({auth:{getSession:()=>Promise.resolve({data:{session:null}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},from:()=>({select:()=>({eq:()=>({range:()=>Promise.resolve({data:[],error:null})})})}),rpc:()=>Promise.resolve({data:[],error:null})})};
}});
const w=dom.window;const ev=e=>{try{return w.eval(e);}catch(x){return 'ERR:'+x.message;}};
let pass=0,fail=0;const ok=(n,c)=>{c?(pass++,console.log('  ✅ '+n)):(fail++,console.log('  ❌ '+n));};
setTimeout(()=>{
 ok('نضيف من غير أخطاء', errs.length===0);
 ok('fatPriceCalc موجودة', typeof w.fatPriceCalc==='function');
 w.fatPriceCalc();
 ok('الحاسبة اتفتحت', !!w.document.getElementById('pcx_cost'));
 ev("document.getElementById('pcx_cost').value='100';document.getElementById('pcx_price').value='150';");
 w.fatPriceCalcRun('price');
 var profit=(w.document.getElementById('pcx_profit')||{}).textContent||'';
 ok('الربح والهامش بيتحسبوا (50 / 33%)', /50/.test(profit)&&/33/.test(profit));
 ev("document.getElementById('pcx_price').value='';document.getElementById('pcx_margin').value='20';");
 w.fatPriceCalcRun('margin');
 ok('من الهامش المستهدف بيطلع السعر (125)', Math.round(+w.document.getElementById('pcx_price').value)===125);
 const inline=(html.match(/<script(?![^>]*\bsrc=)[^>]*>[\s\S]*?<\/script>/gi)||[]).length;
 ok('بلوكين سكربت', inline===2);
 console.log('النتيجة: '+pass+' نجحت · '+fail+' فشلت');
 dom.window.close();process.exit(fail?1:0);
},2500);
